title: Bruno Pulis
email: brunopulis@protonmail.com
description: Procurando um profissional para tornar seus produtos digitais acessíveis? Vamos conversar, minha missão é tornar a web mais simples e acessível
author: Bruno Pulis
baseurl: ""
url: "brunopulis.netlify.com"

# Social Profiles
twitter_username: obrunopulis
linkedin_username: pulis
github_username: brunopulis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

gems: [jekyll-paginate-v2]

# Pagination settings
pagination:
  enabled: true
  per_page: 6
  sort_reverse: true
  sort_field: 'date'
  title: ':title'
  trail:
    before: 2
    after: 2


# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap

collections:
  palestras:
    output: true
    permalink: /palestras/:path/

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# exclude my node related stuff
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache
  - vendor/gems
  - vendor/ruby
