# SITE CONFIGURATION
title: Bruno Pulis
email: brunopulis@protonmail.com
description: Procurando um profissional para tornar seus produtos digitais acessíveis? Vamos conversar, minha missão é tornar a web mais simples e acessível
baseurl: ""
url: "https://brunopulis.com"

# Author Infos
author: Bruno Pulis

# Social Profiles
facebook_username: https://www.facebook.com/obrunopulis
facebook_page: https://www.facebook.com/canaldobrunopulis
twitter_username:  https://twitter.com/obrunopulis
linkedin_username: https://linkedin.com/in/pulis
stackoverflow: https://stackoverflow.com/users/8055146/bruno-pulis
codepen: https://codepen.io/brunopulis
github_username:   https://github.com/brunopulis
medium_username: https://medium.com/@brunopulis
email_username: brunopulis@protonmail.com
youtube_channel: https://www.youtube.com/channel/UCAjuwwxEbHtm4GvVi3W_o6Q
disqus_username: brunopulis

mailchimp_url: "https://brunopulis.us3.list-manage.com/subscribe/post?u=e1843173804aef8e161201c1b&amp;id=806ccbea2e"

webmaster_verifications:
  google: DJZadsIuwm42MwJftKIXWE3cGrZLTlOTYdMf55gIVS8
  bing: A1D6C4C7B86E7BF77A38CFC9B416AD04

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# html minify
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  palestras:
    output: true
    permalink: /palestras/:path/

source: source
destination: _site

sass:
  style: compressed
  sass_dir: source/assets/scss

exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - .bundle/