# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "pt-BR"
title: "Bruno Pulis"
title_separator: "-"
subtitle: "Acessibilidade web, qualidade e frontend"
name: "Bruno Pulis"
description: "Blog de um analista de teste, evangelista de acessibilidade web, javascript, padrões web e novas tecnologias. Escritor nas horas vagas."
url: "https://brunopulis.com"
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: "brunopulis/brunopulis" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser: "/assets/images/teaser-image.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo: "/assets/images/logo.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title: # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs: true # true, false (default)
words_per_minute: 200
comments:
  provider: "disqus"
  disqus:
    shortname: brunopulis
atom_feed:
  path: # blank (default) uses feed.xml
search: true # true, false (default)
search_full_content: # true, false (default)
search_provider: algolia # lunr (default), algolia, google
algolia:
  application_id: MJWV3215SI # YOUR_APPLICATION_ID
  index_name: brunopulis # YOUR_INDEX_NAME
  search_only_api_key: f19e756547d9308962ed97854833f293 # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false

# SEO Related
google_site_verification: DJZadsIuwm42MwJftKIXWE3cGrZLTlOTYdMf55gIVS8
bing_site_verification: A1D6C4C7B86E7BF77A38CFC9B416AD04
yandex_site_verification:
naver_site_verification:

# Social Sharing
twitter:
  username: obrunopulis
facebook:
  username:
  app_id:
  publisher:
og_image: # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type: Person # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/obrunopulis"
    - "https://facebook.com/brunopulis"
    - "https://instagram.com/brunopulis"
    - "https://www.linkedin.com/in/pulis"

# Analytics
analytics:
  provider: google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: UA-39069482-1
    anonymize_ip: true # true, false (default)

# Site Author
author:
  name: "Bruno Pulis"
  avatar: "/assets/images/author.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio: "Escrevo sobre qualidade de software, acessiblidade, desenvolvimento web, carreira e reflexões."
  location: "Belo Horizonte, MG"
  email:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:brunopulis@protonmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/obrunopulis"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/canaldobrunopulis"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brunopulis"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/pulis"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/canaldopulis"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCAjuwwxEbHtm4GvVi3W_o6Q"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/brunopulis"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brunopulis"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/pulis"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy

  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

collections:
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: true

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      read_time: true
      comments: true
      share: true
      related: true

mailchimp_url: "https://brunopulis.us3.list-manage.com/subscribe/post?u=e1843173804aef8e161201c1b&amp;id=806ccbea2e"

source: source
destination: _site
