title: Bruno Pulis
email: brunopulis@protonmail.com
description: Procurando um profissional para tornar seus produtos digitais acessíveis? Vamos conversar, minha missão é tornar a web mais simples e acessível
author: Bruno Pulis
baseurl: ""
url: "brunopulis.com"

webmaster_verifications:
  google: DJZadsIuwm42MwJftKIXWE3cGrZLTlOTYdMf55gIVS8
  bing: A1D6C4C7B86E7BF77A38CFC9B416AD04

# Social Profiles
author:
  name: Bruno Pulis
  twitter: obrunopulis

twitter_username: obrunopulis
linkedin_username: pulis
github_username: brunopulis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Pagination setup
paginate: 6
paginate_path: "blog/page:num/"

# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

collections:
  # portfolio:
  #   output: true
  #   permalink: /portfolio/:path/

  palestras:
    output: true
    permalink: /palestras/:path/

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# exclude my node related stuff
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - .bundle/
