title:             Bruno Pulis
email:             bruno.pulis@gmail.com
description:       Procurando um profissional para tornar seus produtos digitais acessíveis? Vamos conversar, minha missão é tornar a web mais simples e acessível
author:            Bruno Pulis
baseurl:           ""
url:               "brunopulis.netlify.com"

# Social Profiles
twitter_username:  obrunopulis
github_username:   brunopulis
facebook_username: bpulis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page/:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

  palestras:
    output: true
    permalink: /palestras/:path/

# exclude my node related stuff
exclude: [
  'package.json',
  'src',
  'node_modules',
  'vendor/bundle/ruby',
  'package-lock.json',
  'Readme.md',
  'gulpfile.js',
  'initpost.sh',
  'testlinks.sh',
  '.travis.yml'
]
