seo:
  tagline: Acessibilidade Web, Frontend e Qualidade de software
items:
  - link: /
    name: Home
  - link: sobre
    name: Sobre
  - link: blog
    name: Blog
  - link: palestras
    name: Palestras
