seo:
  tagline: Desenvolvedor Web e Evangelista de Acessibilidade Web
items:
  - link: /
    name: Home
  - link: sobre
    name: Sobre
  - link: portfolio
    name: Portfolio
  - link: blog
    name: Blog
  - link: palestras
    name: Palestras
  - link: contato
    name: Contato
