seo:
  tagline: Acessibilidade Web, Frontend e Qualidade de software
items:
  - link: /
    name: Home
  - link: sobre
    name: Sobre
  - link: blog
    name: Blog
  - link: palestras
    name: Palestras
  - link: contato
    name: Contato

jobs:
  yep: No momento estou disponível para novos projetos
  nope: No momento não estou disponível para novos projetos
  nope-class: bg-danger
