backend:
  name: github
  repo: brunopulis/brunopulis
  branch: master

media_folder: "assets/images/posts"
publish_mode: editorial_workflow

collections:
  - name: "website-settings"
    label: "Configurações"
    files:
      - label: "Configurações"
        name: "main"
        file: "_data/main.yml"
        fields:
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Tagline", name: "tagline", widget: "string" }

          - label: "Navegação principal"
            name: "navigation"
            widget: "list"
            fields:
              - { label: "Menu", name: "name", widget: "string" }
              - { label: "URL", name: "link", widget: "string" }

          - label: "Sobre"
            name: "about"
            widget: "object"
            fields:
              - { label: "Cargo", name: "position", widget: "string" }
              - { label: "Descrição", name: "description", widget: "string" }

  - label: "Páginas"
    name: "pages"
    files:
      - label: "About page"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Título",  name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "post"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "featured", widget: "image", default: "assets/images/photo-thumb.jpg" }
      - { label: "Imagem destacada", name: "image", widget: "image", default: "assets/images/posts/cover/" }
      - { label: "Publicado", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma" }
      - { label: "Categoria", name: "categories", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }


